swagger: "2.0"
info:
  version: 1.0.0
  title: Hello World API
basePath: /api/v1

paths:
  /products:
    get:
      summary: Get all products
      responses:
        200:
          description: Products
          schema:
            $ref: '#/definitions/Products'

definitions:
  Products:
    type: array
    items:
      $ref: '#/definitions/Product'

  Product:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
