swagger: "2.0"
info:
  version: 1.0.0
  title: Hello World API
basePath: /api/v1

paths:
  /items:
    get:
      summary: Get all items
      responses:
        200:
          description: Items
          schema:
            $ref: '#/definitions/Items'

definitions:
  Items:
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Item'
  Item:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
